import { AppColors } from './app.colors';

export enum AppDataColors {
  'Altitude' = AppColors.Green,
  'Altitude_0' = AppColors.Green,
  'Altitude_1' = AppColors.LightGreen,
  'Distance' = AppColors.Blue,
  'Depth' = AppColors.LightBlue,
  'Depth_0' = AppColors.LightBlue,
  'Depth_1' = AppColors.Purple,
  'Duration' = AppColors.PurpleBlue,
  'Cadence' = AppColors.DeepBlue,
  'Stroke Rate' = AppColors.DeepBlue,
  'Power' = AppColors.Orange,
  'Power_0' = AppColors.Orange,
  'Power_1' = AppColors.Blue,
  'Power_2' = AppColors.Green,
  'Power_3' = AppColors.Red,
  'Pace' = AppColors.LightBlue,
  'Swim Pace' = AppColors.Blue,
  'Grade Adjusted Pace' = AppColors.PurpleBlue,
  'Pace_0' = AppColors.Blue,
  'Pace_1' = AppColors.Orange,
  'Heart Rate' = AppColors.LightestRed,
  'Heart Rate_0' = AppColors.StrongRed,
  'Heart Rate_1' = AppColors.Purple,
  'Blood Oxygen' = AppColors.LightBlue,
  'Respiration' = AppColors.DeepBlue,
  'Stress' = AppColors.StrongOrange,
  'Body Composition' = AppColors.Pink,
  'Speed' = AppColors.Blue,
  'Speed_0' = AppColors.Blue,
  'Grade Adjusted Speed' = AppColors.DeepBlue,
  'Vertical Speed' = AppColors.Green,
  'VO2 Max' = AppColors.Green,
  'EPOC' = AppColors.Orange,
  'Training Effect' = AppColors.Green,
  'Training Effect_0' = AppColors.Green,
  'Training Effect_1' = AppColors.StrongRed,
  'Recovery Time' = AppColors.Purple,
  'Energy' = AppColors.StrongOrange,
  'Temperature' = AppColors.StrongOrange,
  'Temperature_0' = AppColors.Orange,
}
