import {
  DataAbsolutePressure,
  DataAbsolutePressureAvg,
  DataAbsolutePressureMax,
  DataAbsolutePressureMin,
  DataAccumulatedPower,
  DataAerobicTrainingEffect,
  DataAge,
  DataAirPower,
  DataAirPowerAvg,
  DataAirPowerMax,
  DataAirPowerMin,
  DataAltitudeAvg,
  DataAltitudeMax,
  DataAltitudeMin,
  DataAnaerobicTrainingEffect,
  DataAscent,
  DataAscentTime,
  DataAvgFlow,
  DataAvgGrit,
  DataAvgRespirationRate,
  DataAvgVAM,
  DataBatteryCharge,
  DataBatteryConsumption,
  DataBatteryCurrent,
  DataBatteryVoltage,
  DataCadenceAvg,
  DataCadenceMax,
  DataCadenceMin,
  DataCriticalPower,
  DataDescent,
  DataDescentTime,
  DataDistance,
  DataDuration,
  DataEffortPace,
  DataEHPE,
  DataEHPEAvg,
  DataEHPEMax,
  DataEHPEMin,
  DataEnergy,
  DataEPOC,
  DataEVPE,
  DataEVPEAvg,
  DataEVPEMax,
  DataEVPEMin,
  DataFeeling,
  DataFitnessAge,
  DataFormPower,
  DataFTP,
  DataGender,
  DataGNSSDistance,
  DataGrade,
  DataGradeAdjustedPaceAvg,
  DataGradeAdjustedPaceMax,
  DataGradeAdjustedPaceMin,
  DataGradeAdjustedSpeedAvg,
  DataGradeAdjustedSpeedMax,
  DataGradeAdjustedSpeedMin,
  DataGradeAvg,
  DataGradeMax,
  DataGradeMin,
  DataGrit,
  DataGroundContactTimeAvg,
  DataGroundContactTimeBalanceLeft,
  DataGroundContactTimeBalanceRight,
  DataGroundContactTimeMax,
  DataGroundContactTimeMin,
  DataHeartRateAvg,
  DataHeartRateMax,
  DataHeartRateMin,
  DataHeight,
  DataJumpCount,
  DataJumpDistance,
  DataJumpDistanceAvg,
  DataJumpDistanceMax,
  DataJumpDistanceMin,
  DataJumpHangTimeAvg,
  DataJumpHangTimeMax,
  DataJumpHangTimeMin,
  DataJumpHeightAvg,
  DataJumpHeightMax,
  DataJumpHeightMin,
  DataJumpRotationsAvg,
  DataJumpRotationsMax,
  DataJumpRotationsMin,
  DataJumpScoreAvg,
  DataJumpScoreMax,
  DataJumpScoreMin,
  DataJumpSpeedAvg,
  DataJumpSpeedMax,
  DataJumpSpeedMin,
  DataLegStiffness,
  DataLegStiffnessAvg,
  DataLegStiffnessMax,
  DataLegStiffnessMin,
  DataMaxRespirationRate,
  DataMinRespirationRate,
  DataMovingTime,
  DataNumberOfSatellites,
  DataNumberOfSatellitesAvg,
  DataNumberOfSatellitesMax,
  DataNumberOfSatellitesMin,
  DataPaceAvg,
  DataPeakEPOC,
  DataPower,
  DataPowerAvg,
  DataPowerIntensityFactor,
  DataPowerLeft,
  DataPowerMax,
  DataPowerMin,
  DataPowerNormalized,
  DataPowerPedalSmoothnessLeft,
  DataPowerPedalSmoothnessRight,
  DataPowerPodUsed,
  DataPowerRight,
  DataPowerTorqueEffectivenessLeft,
  DataPowerTorqueEffectivenessRight,
  DataPowerTrainingStressScore,
  DataPowerWattsPerKg,
  DataPowerWork,
  DataRecoveryTime,
  DataRPE,
  DataSatellite5BestSNR,
  DataSatellite5BestSNRAvg,
  DataSatellite5BestSNRMax,
  DataSatellite5BestSNRMin,
  DataSpeedAvg,
  DataStanceTime,
  DataStanceTimeBalanceLeft,
  DataStanceTimeBalanceRight,
  DataStrydDistance,
  DataSwimPaceAvg,
  DataTargetPowerZone,
  DataTemperatureAvg,
  DataTemperatureMax,
  DataTemperatureMin,
  DataTotalGrit,
  DataVerticalOscillation,
  DataVerticalRatio,
  DataVerticalRatioAvg,
  DataVerticalRatioMax,
  DataVerticalRatioMin,
  DataVerticalSpeedAvg,
  DataVO2Max,
  DataWeight,
  DataWPrime,
} from '@sports-alliance/sports-lib';

export type EventSummaryMetricGroupId =
  | 'overall'
  | 'performance'
  | 'altitude'
  | 'environment'
  | 'device'
  | 'physiological'
  | 'other';

export interface EventSummaryMetricGroupConfig {
  id: EventSummaryMetricGroupId;
  label: string;
  metricTypes: string[];
  singleValueTypes?: string[];
}

const POWER_LIB_EXTRA_TYPE_STRINGS: string[] = [
  DataPowerNormalized.type,
  DataPowerIntensityFactor.type,
  DataPowerTrainingStressScore.type,
  DataFTP.type,
  DataPowerWork.type,
  DataPowerWattsPerKg.type,
  DataCriticalPower.type,
  DataWPrime.type,
  DataFormPower.type,
  DataPowerPodUsed.type,
  DataAirPowerAvg.type,
  DataAirPowerMax.type,
  DataAirPowerMin.type,
  DataPowerPedalSmoothnessLeft.type,
  DataPowerPedalSmoothnessRight.type,
  DataPowerTorqueEffectivenessLeft.type,
  DataPowerTorqueEffectivenessRight.type,
  DataTargetPowerZone.type,
];

const ALTITUDE_LIB_EXTRA_TYPE_STRINGS: string[] = [
  DataAscentTime.type,
  DataDescentTime.type,
];

const PHYSIOLOGICAL_EXTRA_TYPE_STRINGS: string[] = [
  DataAvgRespirationRate.type,
  DataMinRespirationRate.type,
  DataMaxRespirationRate.type,
  DataWeight.type,
  DataHeight.type,
  DataGender.type,
  DataFitnessAge.type,
  DataAge.type,
];

const PERFORMANCE_EXTRA_TYPE_STRINGS: string[] = [
  DataEffortPace.type,
  DataAvgVAM.type,
  DataEPOC.type,
  DataAvgFlow.type,
  DataGrit.type,
  DataAvgGrit.type,
  DataTotalGrit.type,
];

const PERFORMANCE_JUMP_TYPE_STRINGS: string[] = [
  DataJumpCount.type,
  DataJumpDistance.type,
  DataJumpDistanceAvg.type,
  DataJumpDistanceMin.type,
  DataJumpDistanceMax.type,
  DataJumpHangTimeAvg.type,
  DataJumpHangTimeMin.type,
  DataJumpHangTimeMax.type,
  DataJumpHeightAvg.type,
  DataJumpHeightMin.type,
  DataJumpHeightMax.type,
  DataJumpSpeedAvg.type,
  DataJumpSpeedMin.type,
  DataJumpSpeedMax.type,
  DataJumpRotationsAvg.type,
  DataJumpRotationsMin.type,
  DataJumpRotationsMax.type,
  DataJumpScoreAvg.type,
  DataJumpScoreMin.type,
  DataJumpScoreMax.type,
];

export const EVENT_SUMMARY_GRADE_ADJUSTED_SPEED_TYPES: string[] = [
  DataGradeAdjustedSpeedAvg.type,
  DataGradeAdjustedSpeedMin.type,
  DataGradeAdjustedSpeedMax.type,
];

export const EVENT_SUMMARY_GRADE_ADJUSTED_PACE_TYPES: string[] = [
  DataGradeAdjustedPaceAvg.type,
  DataGradeAdjustedPaceMin.type,
  DataGradeAdjustedPaceMax.type,
];

const PERFORMANCE_RUN_DYNAMICS_TYPE_STRINGS: string[] = [
  DataGroundContactTimeAvg.type,
  DataGroundContactTimeMin.type,
  DataGroundContactTimeMax.type,
  DataStanceTime.type,
  DataStanceTimeBalanceLeft.type,
  DataStanceTimeBalanceRight.type,
  DataGroundContactTimeBalanceLeft.type,
  DataGroundContactTimeBalanceRight.type,
  DataVerticalOscillation.type,
  DataVerticalRatio.type,
  DataVerticalRatioAvg.type,
  DataVerticalRatioMin.type,
  DataVerticalRatioMax.type,
  DataLegStiffness.type,
  DataLegStiffnessAvg.type,
  DataLegStiffnessMin.type,
  DataLegStiffnessMax.type,
];

const DEVICE_EXTRA_TYPE_STRINGS: string[] = [
  DataBatteryCharge.type,
  DataBatteryConsumption.type,
  DataBatteryCurrent.type,
  DataBatteryVoltage.type,
];

const DEVICE_SIGNAL_EXTRA_TYPE_STRINGS: string[] = [
  DataEVPE.type,
  DataEVPEAvg.type,
  DataEVPEMin.type,
  DataEVPEMax.type,
  DataEHPE.type,
  DataEHPEAvg.type,
  DataEHPEMin.type,
  DataEHPEMax.type,
  DataSatellite5BestSNR.type,
  DataSatellite5BestSNRAvg.type,
  DataSatellite5BestSNRMin.type,
  DataSatellite5BestSNRMax.type,
  DataNumberOfSatellites.type,
  DataNumberOfSatellitesAvg.type,
  DataNumberOfSatellitesMin.type,
  DataNumberOfSatellitesMax.type,
];

const ENVIRONMENT_ABSOLUTE_PRESSURE_TYPE_STRINGS: string[] = [
  DataAbsolutePressure.type,
  DataAbsolutePressureAvg.type,
  DataAbsolutePressureMin.type,
  DataAbsolutePressureMax.type,
];

const ENVIRONMENT_GRADE_TYPE_STRINGS: string[] = [
  DataGrade.type,
  DataGradeAvg.type,
  DataGradeMin.type,
  DataGradeMax.type,
];

const ENVIRONMENT_DISTANCE_TYPE_STRINGS: string[] = [
  DataStrydDistance.type,
  DataGNSSDistance.type,
];

export const EVENT_SUMMARY_DEFAULT_GROUP_ID: EventSummaryMetricGroupId = 'overall';

export const EVENT_SUMMARY_METRIC_GROUPS: EventSummaryMetricGroupConfig[] = [
  {
    id: 'overall',
    label: 'Overall',
    metricTypes: [
      DataDuration.type,
      DataMovingTime.type,
      DataDistance.type,
      DataSpeedAvg.type,
      DataPaceAvg.type,
      DataSwimPaceAvg.type,
      DataHeartRateAvg.type,
      DataPowerAvg.type,
      DataRecoveryTime.type,
      DataVO2Max.type,
      DataAscent.type,
      DataDescent.type,
      DataCadenceAvg.type,
    ],
    singleValueTypes: [
      DataHeartRateAvg.type,
      DataPowerAvg.type,
      DataSpeedAvg.type,
      DataPaceAvg.type,
      DataSwimPaceAvg.type,
      DataCadenceAvg.type,
    ],
  },
  {
    id: 'performance',
    label: 'Performance',
    metricTypes: [
      DataSpeedAvg.type,
      DataPaceAvg.type,
      DataSwimPaceAvg.type,
      ...EVENT_SUMMARY_GRADE_ADJUSTED_PACE_TYPES,
      ...EVENT_SUMMARY_GRADE_ADJUSTED_SPEED_TYPES,
      DataVerticalSpeedAvg.type,
      DataCadenceAvg.type,
      DataCadenceMax.type,
      DataCadenceMin.type,
      DataPower.type,
      DataPowerAvg.type,
      DataPowerMax.type,
      DataPowerMin.type,
      DataPowerLeft.type,
      DataPowerRight.type,
      DataAccumulatedPower.type,
      DataAirPower.type,
      DataHeartRateAvg.type,
      DataHeartRateMax.type,
      DataHeartRateMin.type,
      ...PERFORMANCE_EXTRA_TYPE_STRINGS,
      ...PERFORMANCE_JUMP_TYPE_STRINGS,
      ...PERFORMANCE_RUN_DYNAMICS_TYPE_STRINGS,
      ...POWER_LIB_EXTRA_TYPE_STRINGS,
    ],
    singleValueTypes: [
      DataAvgFlow.type,
    ],
  },
  {
    id: 'altitude',
    label: 'Altitude',
    metricTypes: [],
  },
  {
    id: 'environment',
    label: 'Environment',
    metricTypes: [
      DataAscent.type,
      DataDescent.type,
      ...ALTITUDE_LIB_EXTRA_TYPE_STRINGS,
      DataAltitudeMax.type,
      DataAltitudeMin.type,
      DataAltitudeAvg.type,
      DataTemperatureAvg.type,
      DataTemperatureMax.type,
      DataTemperatureMin.type,
      ...ENVIRONMENT_ABSOLUTE_PRESSURE_TYPE_STRINGS,
      ...ENVIRONMENT_GRADE_TYPE_STRINGS,
      ...ENVIRONMENT_DISTANCE_TYPE_STRINGS,
    ],
  },
  {
    id: 'device',
    label: 'Device',
    metricTypes: [
      ...DEVICE_EXTRA_TYPE_STRINGS,
      ...DEVICE_SIGNAL_EXTRA_TYPE_STRINGS,
    ],
  },
  {
    id: 'physiological',
    label: 'Physiological',
    metricTypes: [
      DataEnergy.type,
      DataVO2Max.type,
      DataPeakEPOC.type,
      DataAerobicTrainingEffect.type,
      DataAnaerobicTrainingEffect.type,
      DataRecoveryTime.type,
      DataFeeling.type,
      DataRPE.type,
      ...PHYSIOLOGICAL_EXTRA_TYPE_STRINGS,
    ],
  },
  {
    id: 'other',
    label: 'Other',
    metricTypes: [],
  },
];

export const EVENT_SUMMARY_DEFAULT_STAT_TYPES: string[] = [
  DataDuration.type,
  DataMovingTime.type,
  DataDistance.type,
  DataSpeedAvg.type,
  ...EVENT_SUMMARY_GRADE_ADJUSTED_SPEED_TYPES,
  ...EVENT_SUMMARY_GRADE_ADJUSTED_PACE_TYPES,
  DataVerticalSpeedAvg.type,
  DataEnergy.type,
  DataPower.type,
  DataPowerAvg.type,
  DataPowerMax.type,
  DataPowerMin.type,
  DataPowerLeft.type,
  DataPowerRight.type,
  DataAccumulatedPower.type,
  DataAirPower.type,
  ...PERFORMANCE_EXTRA_TYPE_STRINGS,
  ...PERFORMANCE_JUMP_TYPE_STRINGS,
  ...PERFORMANCE_RUN_DYNAMICS_TYPE_STRINGS,
  ...POWER_LIB_EXTRA_TYPE_STRINGS,
  DataAscent.type,
  DataDescent.type,
  ...ALTITUDE_LIB_EXTRA_TYPE_STRINGS,
  DataAltitudeMax.type,
  DataAltitudeMin.type,
  DataAltitudeAvg.type,
  DataCadenceAvg.type,
  DataCadenceMax.type,
  DataCadenceMin.type,
  DataTemperatureAvg.type,
  DataTemperatureMax.type,
  DataTemperatureMin.type,
  ...ENVIRONMENT_ABSOLUTE_PRESSURE_TYPE_STRINGS,
  ...ENVIRONMENT_GRADE_TYPE_STRINGS,
  ...ENVIRONMENT_DISTANCE_TYPE_STRINGS,
  ...DEVICE_EXTRA_TYPE_STRINGS,
  ...DEVICE_SIGNAL_EXTRA_TYPE_STRINGS,
  DataHeartRateAvg.type,
  DataHeartRateMax.type,
  DataHeartRateMin.type,
  DataRecoveryTime.type,
  DataPeakEPOC.type,
  DataAerobicTrainingEffect.type,
  DataAnaerobicTrainingEffect.type,
  DataVO2Max.type,
  DataFeeling.type,
  DataRPE.type,
  ...PHYSIOLOGICAL_EXTRA_TYPE_STRINGS,
];
