import "./lib/functions/src/firebase-bootstrap.js";
import {createFirebaseSpanExporter} from "@agentpond/firebase";
import {NodeSDK} from "@opentelemetry/sdk-node";

const telemetry = new NodeSDK({
  traceExporter: createFirebaseSpanExporter(),
});

telemetry.start();

const functions = await import("./lib/functions/src/index.js");

export const addCOROSAPIHistoryToQueue = functions.addCOROSAPIHistoryToQueue;
export const addSuuntoAppHistoryToQueue = functions.addSuuntoAppHistoryToQueue;
export const addSuuntoAppRoutesToQueue = functions.addSuuntoAppRoutesToQueue;
export const aiInsights = functions.aiInsights;
export const backfillActivitySyncRoute = functions.backfillActivitySyncRoute;
export const backfillGarminAPIActivities = functions.backfillGarminAPIActivities;
export const backfillGarminAPISleep = functions.backfillGarminAPISleep;
export const backfillRouteDeliverySyncRoute = functions.backfillRouteDeliverySyncRoute;
export const backfillSuuntoAppSleep = functions.backfillSuuntoAppSleep;
export const checkSubscriptionNotifications = functions.checkSubscriptionNotifications;
export const cleanupEventFile = functions.cleanupEventFile;
export const cleanupRouteFiles = functions.cleanupRouteFiles;
export const cleanupStripeCustomer = functions.cleanupStripeCustomer;
export const cleanupUserAccounts = functions.cleanupUserAccounts;
export const createToolComparisonEvent = functions.createToolComparisonEvent;
export const deauthorizeCOROSAPI = functions.deauthorizeCOROSAPI;
export const deauthorizeGarminAPI = functions.deauthorizeGarminAPI;
export const deauthorizeGarminAPIUsers = functions.deauthorizeGarminAPIUsers;
export const deauthorizeSuuntoApp = functions.deauthorizeSuuntoApp;
export const deleteSelf = functions.deleteSelf;
export const disableActivitySyncRoutesOnCOROSTokenRootDelete = functions.disableActivitySyncRoutesOnCOROSTokenRootDelete;
export const disableActivitySyncRoutesOnGarminTokenRootDelete = functions.disableActivitySyncRoutesOnGarminTokenRootDelete;
export const disableActivitySyncRoutesOnSuuntoTokenRootDelete = functions.disableActivitySyncRoutesOnSuuntoTokenRootDelete;
export const dispatchActivitySyncQueue = functions.dispatchActivitySyncQueue;
export const dispatchRouteDeliverySyncQueue = functions.dispatchRouteDeliverySyncQueue;
export const dispatchSleepSyncQueue = functions.dispatchSleepSyncQueue;
export const enforceSubscriptionLimits = functions.enforceSubscriptionLimits;
export const ensureDerivedMetrics = functions.ensureDerivedMetrics;
export const getAiInsightsQuotaStatus = functions.getAiInsightsQuotaStatus;
export const getCOROSAPIAuthRequestTokenRedirectURI = functions.getCOROSAPIAuthRequestTokenRedirectURI;
export const getFinancialStats = functions.getFinancialStats;
export const getGarminAPIAuthRequestTokenRedirectURI = functions.getGarminAPIAuthRequestTokenRedirectURI;
export const getMaintenanceStatus = functions.getMaintenanceStatus;
export const getQueueStats = functions.getQueueStats;
export const getSubscriptionHistoryTrend = functions.getSubscriptionHistoryTrend;
export const getSuuntoAPIAuthRequestTokenRedirectURI = functions.getSuuntoAPIAuthRequestTokenRedirectURI;
export const getSuuntoFITFile = functions.getSuuntoFITFile;
export const getUpcomingRenewalAmount = functions.getUpcomingRenewalAmount;
export const getUserCount = functions.getUserCount;
export const getUserGrowthTrend = functions.getUserGrowthTrend;
export const impersonateUser = functions.impersonateUser;
export const importActivityToCOROSAPI = functions.importActivityToCOROSAPI;
export const importActivityToSuuntoApp = functions.importActivityToSuuntoApp;
export const importRouteToSuuntoApp = functions.importRouteToSuuntoApp;
export const insertCOROSAPIWorkoutDataToQueue = functions.insertCOROSAPIWorkoutDataToQueue;
export const insertGarminAPIActivityFileToQueue = functions.insertGarminAPIActivityFileToQueue;
export const insertSuuntoAppActivityToQueue = functions.insertSuuntoAppActivityToQueue;
export const insertSuuntoAppRouteToQueue = functions.insertSuuntoAppRouteToQueue;
export const linkExistingStripeCustomer = functions.linkExistingStripeCustomer;
export const listUsers = functions.listUsers;
export const mergeEvents = functions.mergeEvents;
export const onDashboardDerivedMetricsEventWrite = functions.onDashboardDerivedMetricsEventWrite;
export const onSubscriptionUpdated = functions.onSubscriptionUpdated;
export const parseCOROSAPIWorkoutQueue = functions.parseCOROSAPIWorkoutQueue;
export const parseGarminAPIActivityQueue = functions.parseGarminAPIActivityQueue;
export const parseSuuntoAppActivityQueue = functions.parseSuuntoAppActivityQueue;
export const processActivitySyncTask = functions.processActivitySyncTask;
export const processDerivedMetricsIngressTask = functions.processDerivedMetricsIngressTask;
export const processDerivedMetricsTask = functions.processDerivedMetricsTask;
export const processRouteDeliverySyncTask = functions.processRouteDeliverySyncTask;
export const processRouteSyncTask = functions.processRouteSyncTask;
export const processSleepSyncTask = functions.processSleepSyncTask;
export const processSportsLibReparseTask = functions.processSportsLibReparseTask;
export const processSportsLibRouteReparseTask = functions.processSportsLibRouteReparseTask;
export const processWorkoutTask = functions.processWorkoutTask;
export const receiveGarminAPISleepData = functions.receiveGarminAPISleepData;
export const receiveGarminAPIUserPermissions = functions.receiveGarminAPIUserPermissions;
export const receiveSuuntoAppSleepData = functions.receiveSuuntoAppSleepData;
export const refreshCOROSAPIRefreshTokens = functions.refreshCOROSAPIRefreshTokens;
export const refreshGarminAPIRefreshTokens = functions.refreshGarminAPIRefreshTokens;
export const refreshSuuntoAppRefreshTokens = functions.refreshSuuntoAppRefreshTokens;
export const reprocessEvent = functions.reprocessEvent;
export const reprocessRoute = functions.reprocessRoute;
export const requestAndSetCOROSAPIAccessToken = functions.requestAndSetCOROSAPIAccessToken;
export const requestAndSetGarminAPIAccessToken = functions.requestAndSetGarminAPIAccessToken;
export const requestAndSetSuuntoAPIAccessToken = functions.requestAndSetSuuntoAPIAccessToken;
export const restoreUserClaims = functions.restoreUserClaims;
export const retryPendingServiceDisconnects = functions.retryPendingServiceDisconnects;
export const scheduleCOROSSleepSync = functions.scheduleCOROSSleepSync;
export const scheduleSportsLibReparseScan = functions.scheduleSportsLibReparseScan;
export const scheduleSportsLibRouteReparseScan = functions.scheduleSportsLibRouteReparseScan;
export const scheduleSuuntoSleepSync = functions.scheduleSuuntoSleepSync;
export const sendRoutesToService = functions.sendRoutesToService;
export const setEventSharing = functions.setEventSharing;
export const setMaintenanceMode = functions.setMaintenanceMode;
export const stopImpersonation = functions.stopImpersonation;
export const uploadActivity = functions.uploadActivity;
export const uploadRoute = functions.uploadRoute;
