export const GARMIN_API_WORKOUT_QUEUE_COLLECTION_NAME = 'garminAPIActivityQueue';
export const GARMIN_API_TOKENS_COLLECTION_NAME = 'garminAPITokens';

export const GARMIN_REQUIRED_PERMISSIONS = [
    'HISTORICAL_DATA_EXPORT',
    'ACTIVITY_EXPORT',
    'WORKOUT_IMPORT',
    'HEALTH_EXPORT',
    'COURSE_IMPORT',
    'MCT_EXPORT'
];
