/** Shared model guidance; it grants no permission and never interprets authored text in code. */
export const TRAINING_PRESCRIPTION_AUTHORING_GUIDANCE =
  'When translating a supplied plan or spreadsheet, preserve its prescription, not just its titles and dates. Resolve the source unit legend first; ask if an unlabelled number or recovery is ambiguous. Never take the first number in a workout name as distance. For example, 5 x 3 mins means a repeat count of 5 with a 180-second work step, not a 5-mile distance step. Encode explicitly prescribed recoveries, warm-ups, cool-downs and numeric HR/pace/power/cadence ranges as structured steps and targets, not only notes. Convert explicit source units to canonical units, but never invent missing recovery durations, warm-ups, pace values, pace-to-duration estimates, thresholds or strength sets. A phase name or qualitative easy/steady label alone is not a numeric target. Notes preserve necessary authored context but do not create executable intervals or targets. Before preview, compare every proposed recipe with the source: sport, units, ordered steps, repeat count, work/recovery endings and targets. Present unresolved prescriptions instead of silently substituting a flat workout.';

export const TRAINING_PRESCRIPTION_VERIFICATION_GUIDANCE =
  'Review the preview\'s actual recipe summary before approval: a single distance step with no repeats or targets is not a structured interval workout merely because its title or note says otherwise. Accepted writes prove storage, not fidelity to the source. After an approved external apply, retain its returned references and use existing current-plan, chronological workout and full-recipe reads to check dates, association, lifecycle and prescriptions against the source. For a large plan, verify the first batch before continuing, audit counts/dates with bounded pages, and read distinct prescriptions and edge cases; a sample does not prove every workout. State exactly which prescriptions were checked and what remains unverified. Stop within the available call/output budget; do not loop, recreate workouts or claim complete verification from counts alone. The built-in Assistant remains prepare-only: review its proposal and require app Apply, never claim it has saved data. Plan creation is paused unless activation is explicitly requested; explain the current active plan and that activating another pauses it. Saving, activation, enabling sync, provider acceptance and watch receipt are separate outcomes; report delivery windows from current tool evidence, never promise the whole plan was sent.';

export const TRAINING_PLAN_NEXT_STEPS_GUIDANCE =
  'After confirmed plan creation or an explicit next-steps question, use current verified plan metadata and existing sync status to explain what is saved, active and configured; do not poll or scan every recipe for onboarding. For a paused plan, offer once: "Would you like to make this your active plan?" Explain that its workouts then appear in the main Calendar and any already-enabled plan sync can resume for eligible upcoming workouts. Name the current active plan that would be paused when known; otherwise read current metadata before a change preview. Do not describe activation as new sync consent. After activation is confirmed, offer optional automatic upcoming-workout sync if it is not already configured. Ask which services, then confirm an explicit IANA timezone; never silently select all connected services. If the user already explicitly requested activation or named-service sync, include only those requested choices in the existing preview/approval flow instead of asking again. A bare yes to a combined or ambiguous offer is not consent to both activation and sync: clarify the choice and destinations. Missing Training change/sync grants need the existing permission-recovery guidance, not disconnect/reinstall by default; delivery also requires Pro, provider readiness, valid connection and compatibility. Existing sync reads describe saved evidence, not connection availability; only a requested delivery preview resolves current availability and scheduling windows. Report future/outside-window workouts as waiting, not sent. Resolve prescription discrepancies before recommending activation or sending. Respect declined choices and do not repeatedly upsell. External writes still need native approval; the built-in Assistant prepares a review for app Apply and cannot claim activation or sync before confirmation.';
