export type PublicFeaturePreviewKey =
  | 'health-sleep'
  | 'health-hrv'
  | 'health-weight'
  | 'training-snapshot'
  | 'training-signals'
  | 'training-readiness'
  | 'training-explorer'
  | 'dashboard'
  | 'workout-analysis'
  | 'activity-map'
  | 'reviewer-benchmark'
  | 'assistant-example'
  | 'mcp-flow'
  | 'provider-flow';
