export const AI_INSIGHTS_ANOMALY_MIN_BUCKET_COUNT = 6;
export const AI_INSIGHTS_ANOMALY_MIN_MATCHED_EVENTS = 8;
export const AI_INSIGHTS_ANOMALY_MIN_BUCKET_EVENTS = 3;
export const AI_INSIGHTS_ANOMALY_MAX_CALLOUTS = 3;
export const AI_INSIGHTS_ANOMALY_MIX_SHIFT_MAX_SERIES_EVIDENCE = 2;

export const AI_INSIGHTS_ANOMALY_SPIKE_DROP_MEDIUM_Z_SCORE = 2.5;
export const AI_INSIGHTS_ANOMALY_SPIKE_DROP_HIGH_Z_SCORE = 3.5;
export const AI_INSIGHTS_ANOMALY_SPIKE_DROP_MIN_RELATIVE_DELTA = 0.2;

export const AI_INSIGHTS_ANOMALY_MIX_SHIFT_MEDIUM_TVD = 0.3;
export const AI_INSIGHTS_ANOMALY_MIX_SHIFT_HIGH_TVD = 0.45;

export const AI_INSIGHTS_CONFIDENCE_LOW_MAX_SCORE = 0.45;
export const AI_INSIGHTS_CONFIDENCE_MEDIUM_MAX_SCORE = 0.75;
export const AI_INSIGHTS_CONFIDENCE_COVERAGE_WEIGHT = 0.35;
export const AI_INSIGHTS_CONFIDENCE_SAMPLE_WEIGHT = 0.35;
export const AI_INSIGHTS_CONFIDENCE_SIGNAL_WEIGHT = 0.3;
